image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/shoot-cert-service
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
   cpu: "50m"
   memory: "64Mi"
  limits:
   cpu: "50m"
   memory: "128Mi"

vpa:
  enabled: true
  # resourcePolicy:
  #   minAllowed:
  #     cpu: 100m
  #     memory: 128Mi
  updatePolicy:
    updateMode: "Auto"

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false
  healthcheck:
    concurrentSyncs: 5

certificateConfig:
  defaultIssuer:
    restricted: true # restrict default issuer to any sub-domain of shoot.spec.dns.domain
    name: gardener
    acme:
      email: john.doe@example.com
      server: https://acme-v02.api.letsencrypt.org/directory
    # propagationTimeout: 60s # TTL for DNS01 challenges.
    # privateKey: | # Optional key for Let's Encrypt account.
    #   -----BEGIN BEGIN RSA PRIVATE KEY-----
    #   ...
    #   -----END RSA PRIVATE KEY-----

disableControllers: []

# imageVectorOverwrite: |
#   images:
#   - name: cert-management
#     sourceRepository: github.com/gardener/cert-management
#     repository: eu.gcr.io/gardener-project/cert-controller-manager
#     tag: "0.2.9"
