---
apiVersion: v1
kind: Secret
metadata:
  name: ref-some-issuer-custom-eab-hmackey
  namespace: shoot--foo--bar
type: Opaque
data:
  hmacKey: T1RoRFZVeEdkV054eHhiWFpSUldkVzVSYVVkWmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: ref-some-custom-privatekey
  namespace: shoot--foo--bar
type: Opaque
data:
  privateKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeXZhVERxU2lPSngKeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
