apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-logging-config
  namespace: garden
  labels:
    extensions.gardener.cloud/configuration: logging
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                parser
        Match               kubernetes.*cert-controller-manager*shoot-cert-management-seed*
        Key_Name            log
        Parser              certmanagerParser
        Reserve_Data        True

    [FILTER]
        Name                rewrite_tag
        Match               kubernetes.*
        Rule                $tag ^kubernetes\.var\.log\.containers\.(cert-controller-manager-.+?_.+?_shoot-cert-management-seed) user-exposed.$TAG true

  parsers.conf: |-
    [PARSER]
        Name        certmanagerParser
        Format      regex
        Regex       ^time="(?<time>\d{4}-\d{2}-\d{2}T[^"]*)"\s+level=(?<severity>\w+)\smsg="(?<log>.*)"
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S%z
