apiVersion: v1
kind: Service
metadata:
  name: cert-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cert-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.configuration.serverPortHttp }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cert-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
