---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extensions.gardener.cloud:extension-shoot-cert-service:cert-controller-manager
  namespace: {{ .Release.Namespace }}
subjects:
{{- if .Values.useTokenRequestor }}
- kind: ServiceAccount
  name: {{ .Values.shootAccessServiceAccountName }}
  namespace: kube-system
{{- else }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.shootUserName }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extensions.gardener.cloud:extension-shoot-cert-service:cert-controller-manager
